steps:
  # Step 1: Check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/tomas-fpcs/onoff.git']
    dir: '/workspace'

  # Step 2: Set up JDK 17 and build the project with Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/onoff', '.']
    dir: '/workspace/your-repo'

  # Step 4: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/onoff']

  # Step 5: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'your-service-name'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod'
      - '--image'
      - 'gcr.io/$PROJECT_ID/onoff'
      - '--region'
      - 'eu-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/onoff'

options:
  logging: CLOUD_LOGGING_ONLY