spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:onoffdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  autoconfigure:
    exclude:
      - com.my.autoconfigure.filter.OAuth2AuthenticationDetailsFilterAutoConfiguration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

onoff:
  hostname: localhost
  port: 8080
  scheme: http