name: Sync google_checks.xml from checkstyle repo

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Fetch file from external repo
        run: |
          curl -o src/main/resources/google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/refs/heads/master/src/main/resources/google_checks.xml

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/main/resources/google_checks.xml
          git commit -m "Updated google_checks.xml from checkstyle repo" || exit 0
          git remote set-url origin https://github-actions:${{secrets.GH_ACTIONS_TOKEN}}@github.com/tomas-fpcs/onoff.git
          git push
